Array Using Numpy

In [ ]:
# Experiment No. 5

In [1]:
# Name : Om S. Chopar
# Roll : 69
# Sec : A

In [2]:
# Aim : Creation of Array Using Numpy

In [3]:
import random

In [4]:
rm =[random.randint(1,50) for _ in range(15)]

In [5]:
rm

[22, 6, 43, 22, 14, 28, 33, 1, 27, 35, 13, 22, 32, 46, 36]

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
# 1-D Array

In [8]:
arr = np.array([1, 2, 3, 4, 5])

In [9]:
arr

array([1, 2, 3, 4, 5])

In [10]:
# 2-D Array

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [12]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3
